### ISSUE TITLE
How to do batch/bulk image processing?

### ISSUE THREAD

**Issue by noonesperfect** [olaviinha/ImageColorization-colab#1]
Hello , I am quiet new over here and not much familiar with github, but I am trying to do batch processing using

https://colab.research.google.com/github/olaviinha/NeuralImageColorization/blob/master/DeOldify_ImageColorization.ipynb

As i mount "input_dir" as https://drive.google.com/drive/folders/14X5sMmC3pecXYxZIRL9vPYayCayv8IQ9?usp=sharing and
"output_dir" as https://drive.google.com/drive/folders/1Zqmj9Zx0ILl5PSR-GqVK54cL7A2T4Vi9?usp=sharing
It shows following error
AttributeError Traceback (most recent call last)

in ()
12 count = len(pictures)
13
---> 14 op(c.title2, 'Coloring '+str(count)+' images.\n')
15 for i, pic in enumerate(pictures):
16 index = i+1

AttributeError: type object 'c' has no attribute 'title2'

Kindly help, how to work on this for batch processing images. Thanks

**Comment by olaviinha** [comment]
Thanks for reporting! Bug is now fixed, please reload the notebook.

Bug was not related to your inputs, but they are also incorrect: please do not input URL addresses as `input_dir` and `output_dir`, but directory paths. If you have a directory called "grayscale_images" in your Drive, then type simply "grayscale_images" in the `input_dir` field. Same goes for `output_dir` field – e.g. if you have a directory in your drive called "temp", in that directory you have a subdirectory called "colorized_images" where you want to save the colorized images, then type "temp/colorized_images" as `output_dir`.

**Comment by noonesperfect** [comment]
Thanks a lot it get solved. Great work. Bye !
