### ISSUE TITLE
Running the colorize section always outputs 'coloring 0 images'

### ISSUE THREAD

**Issue by superkom** [olaviinha/ImageColorization-colab#2]
Hi. 
I have been trying to use this batch processor for DeOldify, but by copying the path for the imput and output directories into the Colorize section, running the program always outputs the same answer: 'Coloring 0 images'.

Am I doing something wrong or is there a problem with the processer?

Thanks in advance!

**Comment by olaviinha** [comment]
Check that paths are correct.

Correct format of path, example 1:
- In your Google Drive you have a directory called "grayscale-images" that contains grayscale images.
- In this case, your input_dir value should be `grayscale-images`

Example 2:
- In your Google Drive you have a directory called "results", and under that directory you have a subdirectory called "colored-images". This directory is empty and you want to save the colored images under it.
- In this case, your output_dir value should be `results/colored-images`

If these are correct, perhaps it could be something about image format. What format are your images in?

**Comment by superkom** [comment]
That worked perfectly!
I was copying the entire path of the directory, not just the directory name.
Thank you for the clarification.

**Comment by olaviinha** [comment]
Great! You're not the first one, perhaps adding some clearer instructions regarding the paths in the notebook itself would be a good idea...
