### ISSUE TITLE
Error in Setup

### ISSUE THREAD

**Issue by ReedMoon97** [olaviinha/ImageColorization-colab#3]
After granting access to Googe Drive Desktop, I'm getting this this error:
![ScreenHunter_844 Sep  29 13 21](https://user-images.githubusercontent.com/114695589/193123389-3f8ffef4-fc93-4a3b-bf3d-f94ea972c8f9.jpg)

**Comment by olaviinha** [comment]
Thanks for reporting! Looks like original repository had had some updates that broke the notebook. Everything should be now fixed.

**Comment by ReedMoon97** [comment]
Thanks!
